Fix rabbitmq install for RHEL/CentOS
The puppet rabbit module is affected by
https://tickets.puppetlabs.com/browse/MODULES-3599.

On rabbit install, we are seeing error:
Error: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y
install rabbitmq-server-3.6.3-1' returned 1: Error: Package:
rabbitmq-server-3.6.3-1.noarch (rabbitmq_rabbitmq-server)
           Requires: erlang >= R16B-03

Installing package properly before rabbitmq class solves the
install problem for us.

Change-Id: Ie145c70859013c927a3ee0f14c003cca739c996e